---
title: "COC Model Equations"
author: "Eva Dusek Jennings"
date: "June 21, 2021"
output:
  word_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
rm(list=ls(all=T))
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(texreg)
library(here)
library(nlme)
library(huxtable)
library(dplyr)
library(sjPlot)
```


# TSS Models 

```{r}
load(here("results", "TSS Models.RData"))

TSS.null <- gls(data = TSS.coc2, result ~ 1, method = "REML") 
TSS.LU <- lme(data = TSS.coc2, TSS.FormLU, random = TSS.r1X, method = "REML", weights = TSS.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8))
TSS.best <- lme(data = TSS.coc2, TSS.FormBest, random = TSS.r1X, method = "REML", weights = TSS.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8))
```

```{r}

TSS_models <- list(
  TSS.null = TSS.null,
  TSS.LU = TSS.LU,
  TSS.best = TSS.best
)

huxtablereg(TSS_models,
  single.row = TRUE, custom.model.names = names(TSS_models)
) %>%
  set_bottom_border(1, -1, 0.4) %>%
  set_bold(1, -1, TRUE) 
```

```{r}
plotreg(TSS_models, custom.title = "Regression Results, TSS", custom.model.names = names(TSS_models))
```

```{r}
plot_models(TSS_models, m.labels = names(TSS_models), legend.title = "Models", show.values = TRUE,show.intercept = TRUE
              )

```


#Phosphorus Models

```{r}
load(here("results", "Total Phosphorus Models.RData"))

P.null <- gls(data = P.coc2, result ~ 1, method = "REML") 
P.LU <- lme(data = P.coc2, P.FormLU, random = P.r1X, method = "REML", weights = P.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8))
P.best <- lme(data = P.coc2, P.FormBest, random = P.r1X, method = "REML", weights = P.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8))
```

```{r}
P_models <- list(
  P.null = P.null,
  P.LU = P.LU,
  P.best = P.best
)

huxtablereg(P_models,
  single.row = TRUE, custom.model.names = names(P_models)
) %>%
  set_bottom_border(1, -1, 0.4) %>%
  set_bold(1, -1, TRUE) 
```

```{r}
plotreg(P_models, custom.title = "Regression Results, Total Phosphorus", custom.model.names = names(P_models))
```

```{r}
plot_models(P_models, m.labels = names(P_models), legend.title = "Models", show.values = TRUE,show.intercept = TRUE
              )
```


























<!-- # Copper Models -->

<!-- ```{r} -->

<!-- load(here("results", "Copper Models.RData")) -->

<!-- Cu.null <- gls(data = Cu.coc2, result ~ 1, method = "REML") -->
<!-- Cu.M3 <- lme(data = Cu.coc2, result ~ landuse + rain, random = Cu.r1X, method = "REML", weights = Cu.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- Cu.M4 <- lme(data = Cu.coc2, Cu.Form4, random = Cu.r1X, method = "REML", weights = Cu.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- Cu.M5 <- lme(data = Cu.coc2, Cu.Form5, random = Cu.r1X, method = "REML", weights = Cu.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- Cu_models <- list( -->
<!--   Cu.null = Cu.null, -->
<!--   Cu.M3 = Cu.M3, -->
<!--   Cu.M4 = Cu.M4, -->
<!--   Cu.M5 = Cu.M5 -->
<!-- ) -->

<!-- huxtablereg(Cu_models, -->
<!--   single.row = TRUE, custom.model.names = names(Cu_models) -->
<!-- ) %>% -->
<!--   set_bottom_border(1, -1, 0.4) %>% -->
<!--   set_bold(1, -1, TRUE) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plotreg(Cu_models, custom.title = "Regression Results, Total Copper", custom.model.names = names(Cu_models)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot_models(Cu_models[-c(1)],m.labels = names(Cu_models[-c(1)]),legend.title = "Models", show.values = TRUE,show.intercept = TRUE -->
<!--               ) -->

<!-- ``` -->


<!-- # Zinc Models   FIX CODE TO REFLECT ZINC INSTEAD OF NITRITE-NITRATE! -->

<!-- ```{r} -->

<!-- load(here("results", "Zinc Models.RData")) -->

<!-- Zn.null <- gls(data = Zn.coc2, result ~ 1, method = "REML")  -->
<!-- Zn.M3 <- lme(data = Zn.coc2, result ~ landuse + rain, random = Zn.r1X, method = "REML", weights = Zn.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- Zn.M4 <- lme(data = Zn.coc2, Zn.Form4, random = Zn.r1X, method = "REML", weights = Zn.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- Zn.M5 <- lme(data = Zn.coc2, Zn.Form5, random = Zn.r1X, method = "REML", weights = Zn.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- Zn_models <- list( -->
<!--   Zn.null = Zn.null, -->
<!--   Zn.M3 = Zn.M3, -->
<!--   Zn.M4 = Zn.M4, -->
<!--   Zn.M5 = Zn.M5 -->
<!-- ) -->

<!-- huxtablereg(Zn_models, -->
<!--   single.row = TRUE, custom.model.names = names(Zn_models) -->
<!-- ) %>% -->
<!--   set_bottom_border(1, -1, 0.4) %>% -->
<!--   set_bold(1, -1, TRUE)  -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plotreg(Zn_models, custom.title = "Regression Results, Zinc", custom.model.names = names(Zn_models)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot_models(Zn_models[-c(1)],m.labels = names(Zn_models[-c(1)]),legend.title = "Models", show.values = TRUE,show.intercept = TRUE -->
<!--               ) -->

<!-- ``` -->


<!-- # Nitrite-Nitrate Models -->

<!-- ```{r} -->

<!-- load(here("results", "Nitrite_Nitrate Models.RData")) -->

<!-- NO2.null <- gls(data = NO2.coc2, result ~ 1, method = "REML")  -->
<!-- NO2.M3 <- lme(data = NO2.coc2, result ~ landuse + rain, random = NO2.r1X, method = "REML", weights = NO2.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- NO2.M4 <- lme(data = NO2.coc2, NO2.Form4, random = NO2.r1X, method = "REML", weights = NO2.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->
<!-- NO2.M5 <- lme(data = NO2.coc2, NO2.Form5, random = NO2.r1X, method = "REML", weights = NO2.vf1X, control = lmeControl(maxIter = 1e8, msMaxIter = 1e8)) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- NO2_models <- list( -->
<!--   NO2.null = NO2.null, -->
<!--   NO2.M3 = NO2.M3, -->
<!--   NO2.M4 = NO2.M4, -->
<!--   NO2.M5 = NO2.M5 -->
<!-- ) -->

<!-- huxtablereg(NO2_models, -->
<!--   single.row = TRUE, custom.model.names = names(NO2_models) -->
<!-- ) %>% -->
<!--   set_bottom_border(1, -1, 0.4) %>% -->
<!--   set_bold(1, -1, TRUE)  -->
<!-- ``` -->


<!-- ```{r} -->
<!-- plotreg(NO2_models, custom.title = "Regression Results, Nitrite-Nitrate", custom.model.names = names(NO2_models)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot_models(NO2_models[-c(1)],m.labels = names(NO2_models[-c(1)]),legend.title = "Models", show.values = TRUE,show.intercept = TRUE -->
<!--               ) -->

<!-- ``` -->